### Import Necessary Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics.pairwise import cosine_similarity
import warnings
warnings.filterwarnings('ignore')

### Importing the datasets

In [4]:
df = pd.read_csv('movies.csv')
df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

### EDA

In [5]:
df.shape

(62423, 3)

In [6]:
df.isna().sum()

movieId    0
title      0
genres     0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62423 entries, 0 to 62422
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  62423 non-null  int64
 1   title    62423 non-null  object
 2   genres   62423 non-null  object
dtypes: int64(1), object(2)
memory usage: 1.4+ MB

### Feature Processing

In [15]:
df['genres'] = df['genres'].str.split('|').str.join('').str.lower()

# Converting the genres column to vector
vectorizer = TfidfVectorizer()
genre_vector = vectorizer.fit_transform(df['genres'])

### Building the Recommendation System

In [ ]:
def recommendation(title = 'Grumpier Old Men (1995)', top_n = 5):
    # Getting the index of the movie
    idex = df[df['title'] == title].index[0]
    
    # Calculating the similarity of the targeted movie
    similarity = cosine_similarity(genre_vector[idex], genre_vector).flatten()
    
    # Pairing the similarity score with index and sort by scores
    score = list(enumerate(similarity))
    score.sort(key = lambda x: x[1], reverse = True)
    
    # Selecting top_n movies index
    movie_index = [i[0] for i in score[1: top_n + 1]]
    return df[['title']].iloc[movie_index].reset_index(drop = True)
    
    
    





recommendation()

                                title
0                      Sabrina (1995)
1                     Clueless (1995)
2                Two if by Sea (1996)
3  French Twist (Gazon maudit) (1995)
4                 If Lucy Fell (1996)

In [24]:
recommendation('Sabrina (1995)')

                                title
0                      Sabrina (1995)
1                     Clueless (1995)
2                Two if by Sea (1996)
3  French Twist (Gazon maudit) (1995)
4                 If Lucy Fell (1996)